export type SortKey =
  | 'a-z'
  | 'ratings-asc'
  | 'ratings-desc'
  | 'updated-asc'
  | 'updated-desc'
  | 'premiered-asc'
  | 'premiered-desc'
  | 'unrated'

export type GroupKey =
  | 'genres'
  | 'rating'
  | 'premiered-asc'
  | 'ended-asc'
  | 'premiered-desc'
  | 'ended-desc'
  | 'status'
  | 'language'
  | 'network'
  | 'country'
